name: CI/CD Pipeline 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 🔧 Backend install
      - name: 📦 Install backend deps
        run: |
          cd backend
          npm install

      # 🔧 Frontend install + build
      - name: 🎨 Build frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: ✅ Build Success
        run: echo "Pipeline completed successfully 🚀"
